### PR TITLE
add jwst yaml

### PR DESCRIPTION
**Pull request by ttdu**

### CODE REVIEW

**Comment by ttdu** [comment]
@mfox22 Can you confirm hourly updates for JWST? I assumed it would be the same pipeline as HST, but wanted to confirm.

**Comment by mfox22** [comment]
Yes hourly sounds right, once it is in the pipeline.

**Comment by JeffValenti** [comment]
I realize that RequestorPays and License mimic the existing HST entry, but I'll ask anyway...
RequestorPays is False. Will JWST be charged for data transfers?
Does STScI have the authority to grant a license to JWST data?
License text should say "hereby" instead of "herby".

**Comment by ttdu** [comment]
@JeffValenti 

- Users will not be charged for accessing JWST data
- In a sense, it is NASA/ESA/CSA who have the "authority" to select a license. But it is [STScI that sets the policy](https://jwst-docs.stsci.edu/jwst-opportunities-and-policies/jwst-general-science-policies/nasa-smd-policies-and-guidelines-for-the-operations-of-jwst-at-stsci/policy-2-data-rights-and-data-dissemination), with NASA approval. So, as far as I know, this language is ok.
- Typo corrected!

**Comment by JeffValenti** [comment]
Thank for the answers and for correcting the typo (also in HST registry entry). One followup and then I am ready to approve. My question about charges was whether the STScI JWST contract will be charged for data transfers (up or down). I assume no, but want to verify.

**Comment by ttdu** [comment]
I'll submit a separate PR to correct the HST entry as well, thanks for catching that.

Ah, someone **does pay** to move the data and keep it in the cloud. I suspect it is under "JWST-Data Archive" charge,  but I'd need to double check this with Scott Fleming.

**Review by JeffValenti — APPROVED** [review]

**Comment by mfox22** [comment]
Good questions.

As noted we have removed requester pays from our Open Data bucket, all data in our open data bucket is free to download from anywhere in the world.

AWS does not charge to move data into AWS.

The charges for storage and egress are paid by the AWS Open Data program.

**Comment by ttdu** [comment]
Update from @ckaleida: it'll take 1-2 weeks for the JWST backlog transfer to complete after DMS 11.0 goes to Ops on August 27th 

@mfox22: I need a rubber stamp approval on this PR. In fact, having write access would make this process easier; when I open the PR into the AWS repo, I need to "Allow Edits by Maintainers" per their request. I cannot do that with my current privileges.

**Review by mfox22 — APPROVED** [review]
Thanks @ttdu looks good to me.
I notice our fork is 800 commits behind the upstream, so might want to sync those upstream changes before making the PR with the upstream.
Thanks for handling this,
Mike

**Comment by mfox22** [comment]
For update frequency we put an hour, which I think is good for full pipeline integration. But I seem to recall that we are doing this in two phases and for this first phase the updates will be once a week. Then once full integration happens 3 months later we would be at one hour. Might want to verify with @ckaleida

**Pull request merged**
